name: CI & CD for Windows Forms

on:
  push:
    branches: main

jobs:
    build:
        runs-on: windows-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
 
          -
            name: Fetch .NET v7
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: '7.0.x'

          -
            name: Restore .NET 
            run: dotnet restore "${{ github.workspace }}/CaseStudy_DevOps_MoosV_2022.csproj"

          - name: Setup Nuget
            uses: Nuget/setup-nuget@v1.0.5

          - name: Restore NuGet
            run: nuget restore -SolutionDirectory

          -
            name: Build Application 
            run: dotnet build "${{ github.workspace }}/CaseStudy_DevOps_MoosV_2022.csproj" -c Release --no-restore
            
          -
            name: Publish Application 
            run: dotnet publish "${{ github.workspace }}/CaseStudy_DevOps_MoosV_2022.csproj" -c Release -o CaseStudy_DevOps_MoosV_2022
          
          -
            name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: DevOps_artifacts
              path: CaseStudy_DevOps_MoosV_2022/**
              if-no-files-found: error